apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: mieru-config
    files:
      - config/server.json
    options:
      disableNameSuffixHash: true
