apiVersion: v1
kind: Service
metadata:
  name: mieru
  labels:
    app: mieru
spec:
  type: LoadBalancer
  ports:
    - name: mieru-tcp
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: mieru
