apiVersion: v1
kind: Service
metadata:
  name: vpn-gateway
  labels:
    app: vpn-gateway
spec:
  type: NodePort
  selector:
    app: vpn-gateway
  ports:
    - name: wireguard
      port: 51820
      targetPort: wireguard
      nodePort: 31820
      protocol: UDP
