apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: vpn-api-config
    files:
      - config/config.json
    options:
      disableNameSuffixHash: true
