apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-manager-config
data:
  config.json: |
    {
      "server": {
        "host": "0.0.0.0",
        "port": 8080
      },
      "database": {
        "path": "/data/vpn-manager.db"
      },
      "proxy_log": {
        "path": ""
      }
    }
