apiVersion: v1
kind: Service
metadata:
  name: vless-reality
  labels:
    app: vless-reality
spec:
  type: ClusterIP
  ports:
    - name: vless-reality
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: vless-reality
