apiVersion: v1
kind: Service
metadata:
  name: vless-reality
  labels:
    app: vless-reality
spec:
  type: NodePort
  ports:
    - name: vless-reality
      port: 443
      targetPort: 443
      nodePort: 30844
      protocol: TCP
  selector:
    app: vless-reality
