name: Deploy VLESS HTTP

on:
  push:
    branches:
      - main
    paths:
      - 'vless-http/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to stage
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONF }}
        with:
          args: apply -k vless-http/overlays/stage
