name: Rollout Restart

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Application to restart'
        required: true
        default: 'vless-server'
        type: choice
        options:
          - vless-server
          - vless-reality
          - vless-http
          - ss-server
          - vpn-gateway
          - vpn-api

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONF }}
        with:
          args: rollout restart deployment/${{ inputs.app }} -n vpn
