name: Rollout Restart

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Application to restart'
        required: true
        default: 'vless-server'
        type: choice
        options:
          - vless-server
          - vless-reality
          - ss-server
          - vpn-gateway
          - vpn-api

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONF }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Rollout restart
        run: kubectl rollout restart deployment/${{ inputs.app }} -n vless
