apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: shared-pool
  namespace: metallb-system
spec:
  addresses:
    - 37.59.154.7/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: shared-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - shared-pool
