apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vless-http
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: cdn.outi.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vless-http
                port:
                  number: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vless-subscription
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: cdn.outi.ir
      http:
        paths:
          - path: /sub
            pathType: Prefix
            backend:
              service:
                name: vless-subscription
                port:
                  number: 80
