apiVersion: v1
kind: Service
metadata:
  name: vless-http
  labels:
    app: vless-http
spec:
  type: NodePort
  ports:
    - name: vless
      port: 443
      targetPort: vless
      nodePort: 30443
      protocol: TCP
  selector:
    app: vless-http
