apiVersion: v1
kind: ConfigMap
metadata:
  name: vless-subscription
data:
  nginx.conf: |
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;

            location = /sub {
                auth_basic "Subscription";
                auth_basic_user_file /etc/nginx/auth/htpasswd;
            }
        }
    }
  htpasswd: |
    :$2y$05$2KZWmw0R27PkBXJa1vfjkulusvu/M.4NoVR2NIOt80eac/oX3Vdiq
  sub: |
    vless://b831381d-6324-4d53-ad4f-8cda48b30811@cdn.outi.ir:443?security=tls&encryption=none&type=httpupgrade&alpn=h2&host=cdn.outi.ir&path=%2Fvless&sni=cdn.outi.ir#Outi%20CDN
    vless://b831381d-6324-4d53-ad4f-8cda48b30811@static.outi.ir:30843?security=tls&encryption=none&type=httpupgrade&alpn=h2,http/1.1&host=static.outi.ir&path=%2Fvless&sni=static.outi.ir#Outi%20Direct
